[package]
name = "clam5"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]

[dependencies]
failure = "*"
ocl = { git = "https://github.com/cogciprocate/ocl", default-features = false }
png = { version = "*", default-features = false, features = ["png-encoding"] }
sdl2 = "*"
