[package]
name = "clam5"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]
edition = "2018"

[dependencies]
byteorder = "*"
cgmath = "*"
failure = "*"
gl = "*"
lazy_static = "*"
ocl = { version = "*", default-features = false }
openvr = "*"
png = "*"
regex = "*"
sdl2 = { version = "*", default-features = false, features = ["ttf"] }
