[package]
name = "clam5"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]

[dependencies]
failure = "*"
ocl = { version = "*", default-features = false }
png = "*"
sdl2 = { version = "*", default-features = false, features = ["ttf"] }
regex = "*"
lazy_static = "*"
byteorder = "*"
