[package]
name = "clam5"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]
edition = "2018"

[dependencies]
cgmath = ""
chrono = ""
env_logger = ""
futures = ""
glam = ""
png = ""
wgpu = ""
winit = ""

[build-dependencies]
anyhow = ""
fs_extra = ""
glob = ""
shaderc = ""

[profile.release]
debug = true
