[package]
name = "clam5"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]

[dependencies]
glium = { version = "*", default-features = false, features = ["glutin"] }
glium_text_rusttype = { version = "*", default-features = false }
ocl = { version = "*", default-features = false }
ocl-core = { version = "*", default-features = false }
png = { version = "*", default-features = false, features = ["png-encoding"] }
