[package]
name = "clam5"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]
edition = "2018"

[dependencies]
cgmath = "*"
chrono = "*"
failure = "*"
gl = "*"
glutin = "0.22.0-alpha3"
lazy_static = "*"
openvr = { version = "*", optional = true }
png = "*"
regex = "*"
rusttype = "*"

[features]
vr = ["openvr"]