[package]
name = "clam5"
version = "0.1.0"
authors = ["khyperia <khyperia@live.com>"]

[dependencies]
failure = "*"
ocl = { version = "*", default-features = false }
png = { version = "*", default-features = false, features = ["png-encoding"] }
sdl2 = { version = "*", features = ["ttf"] }
